language: c
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libffi-dev
      - pkg-config


script:
  - export VER=$(git describe --always --tags)
  - echo ${VER}

  ###### Install tools ######

  - echo -e "travis_fold:start:build_micropython"
  - echo "Building micropython"
  - git clone --recursive https://github.com/micropython/micropython.git
  - pushd micropython/ports/unix
  - git describe --always --tags
  - make axtls
  - make
  - export PATH=$PATH:$PWD
  - test $(micropython -c 'print("test")') = "test"
  - popd
  - echo -e "travis_fold:end:build_micropython"

  - echo -e "travis_fold:start:build_binutils"
  - echo "Building binutils-esp32ulp"
  - git clone https://github.com/espressif/binutils-esp32ulp.git
  - pushd binutils-esp32ulp
  - git describe --always --tags
  - ./configure --target=esp32ulp-elf --prefix=$PWD/dist --disable-doc --disable-gdb --disable-libdecnumber --disable-readline --disable-sim
  - echo "MAKEINFO = :" >> Makefile
  - make
  - make install-strip
  - export PATH=$PATH:$PWD/dist/bin
  - esp32ulp-elf-as --version | grep 'esp32ulp-elf' > /dev/null
  - popd
  - echo -e "travis_fold:end:build_binutils"

  ###### Run tests ######

  - pushd tests
  
  - echo -e "travis_fold:start:unit_tests"
  - ./00_unit_tests.sh
  - echo -e "travis_fold:end:unit_tests"

  - echo -e "travis_fold:start:compat_tests"
  - ./01_compat_tests.sh
  - echo -e "travis_fold:end:compat_tests"

